return {
    "m4xshen/hardtime.nvim",
    lazy = false,
    dependencies = { "MunifTanjim/nui.nvim" },
    opts = {
        disable_mouse = false,
        max_count = 2,
        restricted_keys = {
            ["h"] = { "n", "x" },
            ["j"] = { "n", "x" },
            ["k"] = { "n", "x" },
            ["l"] = { "n", "x" },
            ["+"] = { "n", "x" },
            ["w"] = { "n", "x" },
            ["W"] = { "n", "x" },
            ["b"] = { "n", "x" },
            ["B"] = { "n", "x" },
            ["e"] = { "n", "x" },
            ["E"] = { "n", "x" },
            ["ge"] = { "n", "x" },
            ["gE"] = { "n", "x" },
            ["gj"] = { "n", "x" },
            ["gk"] = { "n", "x" },
            ["<C-M>"] = { "n", "x" },
            ["<C-N>"] = { "n", "x" },
            ["<C-P>"] = { "n", "x" },
        },
    },
}
