unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on

bind -r , swap-window -t -1 \; select-window -t -1
bind -r . swap-window -t +1 \; select-window -t +1

bind R source-file ~/.tmux.conf \; display "Reloaded!"

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind t new-window -c "~"
bind c new-window -c "#{pane_current_path}"

bind n new-session
bind r "command-prompt -I '#{window_name}' 'rename-window %%'"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g mouse on
